name: cargo_pro_app
description: A production-style Flutter app for CargoPro assignment with Firebase OTP auth and CRUD operations.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management, Navigation, DI
  get: ^4.6.6
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  
  # HTTP & API
  http: ^1.1.2
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Testing
  mocktail: ^1.0.1
  
flutter:
  uses-material-design: true
